##
POST http://localhost:3000/api/motorbike
Content-Type: : application/json

{
  "brand": "Honda",
  "model": "Civic",
  "year": "2018",
  "color": "Red",
  "price": "100000",
  "description": "This is a Honda Civic 2018"
}

###
POST  http://localhost:3000/api/brand
Content-Type: application/json

{
    "name": "dangtuthieu"
}
